In [29]:
import pandas as pd
import numpy as np

In [30]:
df = pd.read_excel("../data/raw/superstore_clean.xls")

In [32]:
print("Rows, Columns:", df.shape)

df.head()

Rows, Columns: (10194, 21)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [33]:
df.info

<bound method DataFrame.info of        Row ID        Order ID Order Date  Ship Date       Ship Mode  \
0           1  US-2023-103800 2023-01-03 2023-01-07  Standard Class
1           2  US-2023-112326 2023-01-04 2023-01-08  Standard Class
2           3  US-2023-112326 2023-01-04 2023-01-08  Standard Class
3           4  US-2023-112326 2023-01-04 2023-01-08  Standard Class
4           5  US-2023-141817 2023-01-05 2023-01-12  Standard Class
...       ...             ...        ...        ...             ...
10189   10190  US-2026-143259 2026-12-30 2027-01-03  Standard Class
10190   10191  US-2026-115427 2026-12-30 2027-01-03  Standard Class
10191   10192  US-2026-156720 2026-12-30 2027-01-03  Standard Class
10192   10193  US-2026-143259 2026-12-30 2027-01-03  Standard Class
10193   10194  CA-2026-143500 2026-12-30 2027-01-03  Standard Class

      Customer ID      Customer Name      Segment Country/Region  \
0        DP-13000      Darren Powers     Consumer  United States
1        PO-19195      Phillina Ober  Home Office  United States
2        PO-19195      Phillina Ober  Home Office  United States
3        PO-19195      Phillina Ober  Home Office  United States
4        MB-18085         Mick Brown     Consumer  United States
...           ...                ...          ...            ...
10189    PO-18865  Patrick O'Donnell     Consumer  United States
10190    EB-13975         Erica Bern    Corporate  United States
10191    JM-15580      Jill Matthias     Consumer  United States
10192    PO-18865  Patrick O'Donnell     Consumer  United States
10193    HO-15230        Harry Olson     Consumer         Canada

                City  ... Postal Code   Region       Product ID  \
0            Houston  ...       77095  Central  OFF-PA-10000174
1         Naperville  ...       60540  Central  OFF-BI-10004094
2         Naperville  ...       60540  Central  OFF-LA-10003223
3         Naperville  ...       60540  Central  OFF-ST-10002743
4       Philadelphia  ...       19143     East  OFF-AR-10003478
...              ...  ...         ...      ...              ...
10189  New York City  ...       10009     East  OFF-BI-10003684
10190      Fairfield  ...       94533     West  OFF-BI-10004632
10191       Loveland  ...       80538     West  OFF-FA-10003472
10192  New York City  ...       10009     East  TEC-PH-10004774
10193  Charlottetown  ...         C0A     East  OFF-BI-10004040

              Category Sub-Category  \
0      Office Supplies        Paper
1      Office Supplies      Binders
2      Office Supplies       Labels
3      Office Supplies      Storage
4      Office Supplies          Art
...                ...          ...
10189  Office Supplies      Binders
10190  Office Supplies      Binders
10191  Office Supplies    Fasteners
10192       Technology       Phones
10193  Office Supplies      Binders

                                            Product Name    Sales  Quantity  \
0      Message Book, Wirebound, Four 5 1/2" X 4" Form...   16.448         2
1             GBC Standard Plastic Binding Systems Combs    3.540         2
2                                              Avery 508   11.784         3
3                          SAFCO Boltless Steel Shelving  272.736         3
4      Avery Hi-Liter EverBold Pen Style Fluorescent ...   19.536         3
...                                                  ...      ...       ...
10189               Wilson Jones Legal Size Ring Binders   52.776         3
10190                                 GBC Binding covers   20.720         2
10191                                Bagged Rubber Bands    3.024         3
10192                          Gear Head AU3700S Headset   90.930         7
10193                        Wilson Jones Impact Binders    3.024         3

       Discount   Profit
0           0.2   5.5512
1           0.8  -5.4870
2           0.2   4.2717
3           0.2 -64.7748
4           0.2   4.8840
...         ...      ...
10189       0.2  19.7910
10190       0.2   6.4750
10191       0.2  -0.6048
10192       0.0   2.7279
10193       0.2  -0.6048

[10194 rows x 21 columns]>

In [34]:
print(df.columns.tolist())

['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City', 'State/Province', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']

In [35]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

In [37]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [38]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

In [39]:
df["Order Year"] = df["Order Date"].dt.year

In [40]:
df["Order Month"] = df["Order Date"].dt.month_name()

In [41]:
df["Quarter"] = df["Order Date"].dt.quarter

In [42]:
df["Shipping Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

In [ ]:
df["Profit Margin"] = (
    df["Profit"] / df["Sales"]
) * 100

In [45]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Product Name,Sales,Quantity,Discount,Profit,Order Year,Order Month,Quarter,Shipping Days,Profit Margin
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512,2023,January,1,4,33.75
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870,2023,January,1,4,-155.00
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Avery 508,11.784,3,0.2,4.2717,2023,January,1,4,36.25
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748,2023,January,1,4,-23.75
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840,2023,January,1,7,25.00

In [46]:

print(df.shape)

df.info()

(10194, 26)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  datetime64[ns]
 3   Ship Date       10194 non-null  datetime64[ns]
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  object
 6   Customer Name   10194 non-null  object
 7   Segment         10194 non-null  object
 8   Country/Region  10194 non-null  object
 9   City            10194 non-null  object
 10  State/Province  10194 non-null  object
 11  Postal Code     10194 non-null  object
 12  Region          10194 non-null  object
 13  Product ID      10194 non-null  object
 14  Category        10194 non-null  object
 15  Sub-Category    10194 non-null  object
 16  Product Name    10194 non-null  object
 17  Sales           10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
 21  Order Year      10194 non-null  int32
 22  Order Month     10194 non-null  object
 23  Quarter         10194 non-null  int32
 24  Shipping Days   10194 non-null  int64
 25  Profit Margin   10194 non-null  float64
dtypes: datetime64[ns](2), float64(4), int32(2), int64(3), object(15)
memory usage: 1.9+ MB

In [47]:


import os

os.makedirs("../data/cleaned", exist_ok=True)

In [48]:
df.to_csv(
    "../data/cleaned/superstore_final.csv",
    index=False
)

print("Cleaned Data Saved Successfully")

Cleaned Data Saved Successfully

In [49]:
import os

print(os.listdir("../data/cleaned"))

['superstore_clean.csv', 'superstore_final.csv']

In [2]:
import os

os.makedirs("../data/cleaned", exist_ok=True)
os.makedirs("../exports", exist_ok=True)
os.makedirs("../models", exist_ok=True)